@startuml
!theme reddress-lightred

start
	:Рассчитанные параметры;
  -> Результат работы модели объекта;

  :Найти зависимые элементы \nформы или свойства;
  -> Зависимость определяется 
  как составом входящих параметров
  функции состояния, так и параметрами, 
  определяющими значения свойств элемента;

repeat
  :Выбрать элемент по порядку;
  -> Порядок элемента может определяться,
  если элемент входит 
  в различные группировки;
    if (Это свойство?) then (Да)
      :Установить \nзначение свойства;
	  -> Не все свойства 
	  можно установить!;

    else (Нет)
	  :Определить состав \nи значения свойств элемента;
    endif

    ->;

repeat while (Следующий элемент?) is (да) not (нет)

stop

@enduml
