@startuml
!theme reddress-lightred
participant Контролер [
    =Контролер
    ----
    ""Controller""
]
participant МодельОбъекта [
    =Модель объекта
    ----
    ""Model""
]
participant МодельФормы [
    =Модель формы
    ----
    ""View""
]
Контролер -> МодельОбъекта: Измененные параметры
МодельОбъекта -> МодельФормы: Рассчитанные параметры
@enduml