@startuml
!theme reddress-lightred

start
	:Измененные параметры;
  -> Изменения параметров \nиз интерфейса;
repeat

  :Найти зависимые параметры;
  -> Измененные и зависимые параметры
  рассчитываются в общей последовательности
  по порядку;
  :Выбрать первый параметр по порядку;

    if (Параметр изменен?) then (Да)
      :При изменении;
	  -> Возможно будут добавлены
	   еще измененные параметры;

    else (Нет)
	  :Определить значение параметра;
    endif

    ->;

repeat while (Есть измененные \nили \nнеобработанные \nпараметры?) is (да) not (нет)

	:Рассчитанные параметры;

stop

@enduml